namespace Qurre.API.Objects
{
    public enum RoomType
    {
        Unknown = 0,
        LczArmory = 1,
        LczCurve = 2,
        LczStraight = 3,
        Lcz330 = 4,
        Lcz914 = 5,
        LczCrossing = 6,
        LczTCross = 7,
        LczCafe = 8,
        LczPlants = 9,
        LczToilets = 10,
        LczAirlock = 11,
        Lcz173 = 12,
        LczClassDSpawn = 13,
        LczChkpB = 14,
        LczGr18 = 15,
        LczChkpA = 16,
        Hcz079 = 17,
        HczEzCheckpoint = 18,
        HczArmory = 19,
        Hcz939 = 20,
        HczHid = 21,
        Hcz049 = 22,
        HczChkpA = 23,
        HczCrossing = 24,
        HczStraight = 25,
        Hcz106 = 26,
        HczNuke = 27,
        HczTesla = 28,
        HczServers = 29,
        HczChkpB = 30,
        HczTCross = 31,
        HczCurve = 32,
        Hcz096 = 33,
        EzVent = 34,
        EzIntercom = 35,
        EzGateA = 36,
        EzDownstairsPcs = 37,
        EzCurve = 38,
        EzPcs = 39,
        EzCrossing = 40,
        EzThreeWay = 41,
        EzCollapsedTunnel = 42,
        EzConference = 43,
        EzStraight = 44,
        EzCafeteria = 45,
        EzUpstairsPcs = 46,
        EzGateB = 47,
        EzShelter = 48,
        Pocket = 49,
        Surface = 50
    }
}