namespace Qurre.API.Objects
{
    public enum RoomType
    {
        Unknown = 0,
        LczArmory = 1,
        LczCurve = 2,
        LczStraight = 3,
        Lcz012 = 4,
        Lcz914 = 5,
        LczCrossing = 6,
        LczTCross = 7,
        LczCafe = 8,
        LczPlants = 9,
        LczToilets = 10,
        LczAirlock = 11,
        Lcz173 = 12,
        LczClassDSpawn = 13,
        LczChkpB = 14,
        Lcz372 = 15,
        LczChkpA = 16,
        Hcz079 = 17,
        HczEzCheckpoint = 18,
        HczArmory = 19,
        Hcz939 = 20,
        HczHid = 21,
        Hcz049 = 22,
        HczChkpA = 23,
        HczCrossing = 24,
        Hcz106 = 25,
        HczNuke = 26,
        HczTesla = 27,
        HczServers = 28,
        HczChkpB = 29,
        HczTCross = 30,
        HczCurve = 31,
        Hcz096 = 32,
        EzVent = 33,
        EzIntercom = 34,
        EzGateA = 35,
        EzDownstairsPcs = 36,
        EzCurve = 37,
        EzPcs = 38,
        EzCrossing = 39,
        EzCollapsedTunnel = 40,
        EzConference = 41,
        EzStraight = 42,
        EzCafeteria = 43,
        EzUpstairsPcs = 44,
        EzGateB = 45,
        EzShelter = 46,
        Pocket = 47,
        Surface = 48
    }
}
